export enum NotificationType {
  MESSAGE = 'message',
  EVENT = 'event',
  ANNOUNCEMENT = 'announcement',
  EVENT_REMINDER = 'event_reminder',
  PAYMENT_REMINDER = 'payment_reminder',
  CUSTOM = 'custom',
  ORDER = 'order',
  PAYMENT = 'payment',
  SUBSCRIPTION = 'subscription',
  DONATION = 'donation',
  VOLUNTEER = 'volunteer',
  TRAINING = 'training',
  REPLY = 'reply',
}
