name: cmda-backend
services:
  - name: cmda-backend
    build_command: npm run build
    run_command: npm run start:prod
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
