name: cmda-backend
services:
  - name: cmda-backend
    build_command: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm run build
    run_command: pnpm run start:prod
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
